import Foundation
import AppKit
import ApplicationServices

// MARK: - AX helpers
func axString(_ el: AXUIElement, _ attr: String) -> String? {
    var ref: CFTypeRef?
    if AXUIElementCopyAttributeValue(el, attr as CFString, &ref) == .success,
       let s = ref as? String, !s.isEmpty { return s }
    return nil
}
func axChild(_ el: AXUIElement, _ attr: String) -> AXUIElement? {
    var ref: CFTypeRef?
    if AXUIElementCopyAttributeValue(el, attr as CFString, &ref) == .success,
       let r = ref, CFGetTypeID(r) == AXUIElementGetTypeID() { return (r as! AXUIElement) }
    return nil
}

enum Capture {
    /// One AX-tree observation of the frontmost window.
    /// Screen content is `ocr` -> untrusted: the AX tree of a webpage is whatever the page
    /// says. Trust is assigned by capture path, not by how convenient it would be.
    static func focus(store: Store) -> Event? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        let bundle = app.bundleIdentifier ?? ""
        let appName = app.localizedName ?? bundle

        var title = ""
        let axApp = AXUIElementCreateApplication(app.processIdentifier)
        if let win = axChild(axApp, kAXFocusedWindowAttribute) {
            title = axString(win, kAXTitleAttribute) ?? ""
        }
        if title.isEmpty,
           let infos = CGWindowListCopyWindowInfo([.optionOnScreenOnly], kCGNullWindowID) as? [[String: Any]] {
            for w in infos where (w[kCGWindowOwnerPID as String] as? pid_t) == app.processIdentifier {
                if let n = w[kCGWindowName as String] as? String, !n.isEmpty { title = n; break }
            }
        }

        // exclusion BEFORE reading any content
        if case .deny(let rule) = Exclusion.check(bundle: bundle, title: title) {
            store.recordExclusion(rule: rule, bundle: bundle, app: appName)
            var e = Event(source: "exclusion.suppressed", sourceKind: .ownFile)
            e.app = appName; e.bundle = bundle
            e.title = "[suppressed: \(rule)]"
            return e                                        // THAT it happened, never WHAT
        }

        var role = "", text = ""
        if let el = axChild(axApp, kAXFocusedUIElementAttribute) {
            role = axString(el, kAXRoleAttribute) ?? ""
            text = axString(el, kAXSelectedTextAttribute)
                ?? axString(el, kAXValueAttribute)
                ?? axString(el, kAXDescriptionAttribute) ?? ""
            if text.count > 4000 { text = String(text.prefix(4000)) }
        }
        let (clean, _) = Exclusion.redact(text)
        if title.isEmpty && clean.isEmpty { title = appName }

        var e = Event(source: "ax.focus", sourceKind: .ocr)
        e.app = appName; e.bundle = bundle; e.title = title; e.role = role; e.text = clean
        return e
    }

    /// Clipboard. Polling `changeCount` costs 451 ns/call measured — a non-issue at 5–10 Hz.
    /// The part that matters is the flags: never record a payload marked concealed.
    /// `lastChange` starts at -1 so the FIRST tick always evaluates the current
    /// clipboard. Initialising it to the live changeCount (the obvious thing) means a
    /// one-shot run can never observe anything, which is a silent no-op.
    static func clipboard(store: Store, lastChange: inout Int) -> Event? {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return nil }
        lastChange = pb.changeCount
        let types = pb.types?.map(\.rawValue) ?? []

        for marker in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                       "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
                       "de.petermaurer.TransientPasteboardType"] where types.contains(marker) {
            store.recordExclusion(rule: "pasteboard:\(marker)", bundle: "", app: "clipboard")
            return nil                                       // timestamp only, no payload
        }
        guard let s = pb.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !s.isEmpty else { return nil }
        let (clean, nred) = Exclusion.redact(s)
        if clean.isEmpty || nred > 0 {
            store.recordExclusion(rule: "pasteboard:secret-shaped", bundle: "", app: "clipboard")
            return nil
        }
        let src = types.first { $0 == "org.chromium.source-url" }
        var e = Event(source: "clipboard", sourceKind: .ocr)   // origin unknown -> untrusted
        // external_id = content hash, so restarting exo re-reads the same clipboard
        // without duplicating it (the unique index on (source, external_id) absorbs it)
        e.externalID = sha(clean)
        e.app = NSWorkspace.shared.frontmostApplication?.localizedName ?? ""
        e.bundle = NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? ""
        e.title = "clipboard"
        e.text = String(clean.prefix(8000))
        if let src { e.meta["origin"] = src }
        return e
    }
}
